name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install ruff mypy
      - name: ruff
        run: |
          ruff --version
          ruff check matcalc
          ruff format matcalc --check
      - name: mypy
        run: |
          mypy --version
          rm -rf .mypy_cache
          mypy matcalc
